---
# tasks file for fail2ban_master
- name: Include OS specific tasks for fail2ban
  include_tasks: "{{ ansible_os_family }}.yml"

- name: kmow state0 of fail2ban
  command: systemctl status fail2ban
  register: print
  failed_when: print.rc == 44

- name: copy file
  become: yes
  template: src={{ path_file }}/jail.local.j2 dest={{ dest }}/jail.local mode=0555

- name: start fail2ban
  become: yes
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: kmow state of fail2ban
  command: systemctl status fail2ban
  register: print
  ignore_errors: True
  notify: print state of fail2ban
...
