---
# tasks file for fail2ban_master
- block: # ==== for ubuntu ==== #
  - name: update
    apt:
      update_cache: yes
  - name: Install fail2ban
    apt:
      name: fail2ban
      state: present
  when: ansible_os_family == 'Debian'

- block: # ==== for CentOs ==== #
  - name: update yum
    yum:
      update_cache: yes
  - name: Install fail2ban
    yum:
      name: fail2ban
      state: present
  when: ansible_os_family == 'RedHat'

- name: copy file
  copy: src={{ path_file }} dest={{ dest }} mode=0555
  notify: start fail2ban

- name: kmow state of fail2ban
  shell: systemctl status fail2ban | grep -i "active:"
  register: print

- name: print state of fail2ban
  debug:
    var: print.stdout
...
